CREATE TABLE yachts (
    id                      SERIAL PRIMARY KEY,
    name                    VARCHAR,
    listing_for_charter     BOOLEAN,
    listing_for_sale        BOOLEAN,
    build_year              VARCHAR,
    refit_year              VARCHAR,
    length                  NUMERIC,
    master_cabins           NUMERIC DEFAULT 0,
    double_cabins           NUMERIC DEFAULT 0,
    twin_cabins             NUMERIC DEFAULT 0,
    triple_cabins           NUMERIC DEFAULT 0,
    single_cabins           NUMERIC DEFAULT 0,
    extra_bunk_bed          NUMERIC DEFAULT 0,
    number_of_cabins        NUMERIC,
    number_of_passengers    NUMERIC,
    sale_price              DOUBLE PRECISION,
    inclusive_terms         TEXT,
    additional_costs        TEXT,
    created_at              DATE NOT NULL,
    updated_at              DATE NOT NULL,
    category                VARCHAR,
    images                  json,
    about                   TEXT,
    accommodation           TEXT,
    entertainment           TEXT,
    featured_title_1        VARCHAR,
    featured_description_1  VARCHAR,
    featured_image_1        VARCHAR,
    featured_title_2        VARCHAR,
    featured_description_2  VARCHAR,
    featured_image_2        VARCHAR,
    featured_title_3        VARCHAR,
    featured_description_3  VARCHAR,
    featured_image_3        VARCHAR,
    featured_title_4        VARCHAR,
    featured_description_4  VARCHAR,
    featured_image_4        VARCHAR,
    featured_title_5        VARCHAR,
    featured_description_5  VARCHAR,
    featured_image_5        VARCHAR,
    video                   VARCHAR,
    main_image              VARCHAR,
    no_of_members           NUMERIC,
    side_images             VARCHAR,
    slug                    VARCHAR,
    approved                BOOLEAN,
    confirmable             BOOLEAN,
    charter_price           DOUBLE PRECISION
);
